services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    depends_on:
      - api

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - QUEUE_ATTEMPTS=3
      - QUEUE_REMOVE_COMPLETE=false
      - QUEUE_REMOVE_FAIL=false
      - QUEUE_JOB_TTL=86400
    volumes:
      - ./shared:/app/shared
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 5
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./shared:/app/shared
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  shared: 