services:
  nginx:
    image: ${REGISTRY:-localhost}/mp4-to-gif-nginx:${TAG:-latest}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/upload.conf:/etc/nginx/conf.d/upload.conf:ro
    depends_on:
      - api
      - client

  client:
    image: ${REGISTRY:-localhost}/mp4-to-gif-client:${TAG:-latest}
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app-network

  api:
    image: ${REGISTRY:-localhost}/mp4-to-gif-api:${TAG:-latest}
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - shared-storage:/app/shared

  worker:
    image: ${REGISTRY:-localhost}/mp4-to-gif-worker:${TAG:-latest}
    build:
      context: ./worker
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - shared-storage:/app/shared

  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-storage:
    driver: local